const test = require("node:test")
const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const root = path.join(__dirname, "..")
const read = name => fs.readFileSync(path.join(root, name), "utf8")

test("marketplace copy uses the full contract and tells one truthful story", () => {
  const manifest = JSON.parse(read("manifest.json"))
  assert.equal(manifest.description.length, 500)
  assert.equal(manifest.barWidget.description.length, 500)
  assert.equal(manifest.barWidget.description, manifest.description)
  assert.match(manifest.description, /The bar counts captures/)
  assert.match(manifest.description, /open the panel for the newest 24/)
  assert.match(manifest.description, /refreshes every 20 seconds/)
  assert.match(manifest.description, /never reads image pixels/)
  assert.match(manifest.description, /uses the network/)
})

test("banner names and visually explains Capture Conveyor without invented actions", () => {
  const banner = read("assets/banner.svg")
  assert.match(banner, /<title id="title">Capture Conveyor<\/title>/)
  assert.match(banner, /4 RECENT CAPTURES/)
  assert.match(banner, /NEW CAPTURE/)
  assert.match(banner, /OCR SELECT/)
  assert.match(banner, /COPY PATH/)
  assert.match(banner, /REVEAL/)
  assert.doesNotMatch(banner, /ANNOTATE/)
})

test("real-shell preview is deterministic, full-frame, and seeded before startup", () => {
  const panel = read("Panel.qml")
  const render = read("scripts/rig-render.sh")
  const hook = read("e2e/rig-before-shell.sh")
  assert.match(panel, /contentWidth:\s*panel\.fittedContentWidth\(Style\.space\(560\)\)/)
  assert.match(panel, /Saved by Omarchy\. Select one to copy its path or reveal its folder\./)
  assert.match(render, /OMARCHY_RIG_RESOLUTION:-1280x720/)
  assert.match(render, /-path '\.\/e2e\/\*'/)
  assert.match(render, /PRE_HOOK=.*rig-before-shell\.sh/)
  assert.match(render, /grim "\\\$SHOT"/)
  assert.doesNotMatch(render, /grim -g/)
  assert.match(hook, /screenshot-launch-dashboard\.png/)
  assert.match(hook, /screenshot-terminal-proof\.png/)
  assert.match(hook, /\.captures \| length == 6/)
  assert.doesNotMatch(hook, /curl|wget|Authorization|Bearer/)
  assert.equal(fs.statSync(path.join(root, "e2e/rig-before-shell.sh")).mode & 0o111, 0o111)
})
